# Etapa de construcción
FROM python:3.11-slim AS build

WORKDIR /app

# Copiar los archivos necesarios
COPY src/requirements.txt ./

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Etapa final
FROM python:3.11-slim AS production

WORKDIR /app

# Copiar el código del backend desde la carpeta src
COPY src/ ./

# Copiar las dependencias instaladas de la etapa anterior
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /usr/local/bin /usr/local/bin

# Configurar variables de entorno
ENV PORT=8000
EXPOSE $PORT

# Crear usuario sin privilegios
RUN adduser --disabled-password --gecos '' myuser
RUN chown -R myuser:myuser /app
USER myuser

# Ejecutar el backend
CMD ["/usr/local/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]